unit YF.SOAP.Constants;

interface

const
  // YFRC (YellowFin Request Constants)
  YRC_GETALLUSERREPORTS = 'GETALLUSERREPORTS';
  YRC_GETUSERREPORTS = 'GETUSERREPORTS';
  YRC_GETUSERDRAFTREPORTS = 'GETUSERDRAFTREPORTS';
  YRC_GETFAVOURITES = 'GETFAVOURITES';
  YRC_FILTEROPTIONS = 'FILTEROPTIONS';

  YRC_ADDTOFAVOURITES ='ADDTOFAVOURITES';
  YRC_REMOVEFAVOURITE = 'REMOVEFAVOURITE';

  YRC_SCHEMA = 'SCHEMA';

  // USER Management
  YRC_ADDUSER = 'ADDUSER';
  YRC_DELETEUSER = 'DELETEUSER';
  YRC_GETUSER = 'GETUSER';
  YRC_GETUSERBYIP = 'GETUSERBYIP';
  YRC_GETUSERFROMSEARCH = 'GETUSERFROMSEARCH';
  YRC_VALIDATEUSER = 'VALIDATEUSER';
  YRC_VALIDATEPASSWORD = 'VALIDATEPASSWORD';
  YRC_CHANGEPASSWORD = 'CHANGEPASSWORD';
  YRC_LOGINUSER = 'LOGINUSER';

  // Report Request - https://wiki.yellowfinbi.com/display/yfcurrent/Report+Format+Services
  YRR_CSV  = 'CSV';
  YRR_HTML = 'HTML';
  YRR_PDF  = 'PDF';
  YRR_XLS  = 'XLS';
  YRR_XLSX  = 'XLSX';

  // YellowFin Result Status
  YRS_SUCCESS = 'SUCCESS';
  YRS_FAILURE = 'FAILURE';

  // YellowFin Report Filter Display Types
  YRFDT_DROPDOWN = 'DROPDOWN';
  YRFDT_DATE = 'DATE';
  YRFDT_TEXT = 'TEXT';
  YRFDT_NUMERIC_SLIDER = 'NUMERIC_SLIDER';


implementation

end.
